"""initial

Revision ID: 0001
Revises:
Create Date: 2026-07-30 12:05:39.923913
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_permissions",
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner','admin','cskh','ketoan')", name=op.f("ck_admin_permissions_role")
        ),
        sa.PrimaryKeyConstraint("role", "command", name=op.f("pk_admin_permissions")),
    )
    op.create_table(
        "asn_policy",
        sa.Column("asn", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("network_class", sa.Text(), nullable=False),
        sa.Column("max_accounts", sa.Integer(), nullable=False),
        sa.Column("window_hours", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "network_class IN ('mobile_cgnat', 'residential', 'hosting', 'vpn')",
            name=op.f("ck_asn_policy_network_class_allowed"),
        ),
        sa.CheckConstraint(
            "max_accounts >= 0", name=op.f("ck_asn_policy_max_accounts_non_negative")
        ),
        sa.CheckConstraint("window_hours > 0", name=op.f("ck_asn_policy_window_hours_positive")),
        sa.PrimaryKeyConstraint("asn", name=op.f("pk_asn_policy")),
    )
    op.create_table(
        "audit_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('admin','system')", name=op.f("ck_audit_log_actor_type")
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "broadcast_jobs",
        sa.Column("job_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sent", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "audience IN ('active_30d','all','custom')", name=op.f("ck_broadcast_jobs_audience")
        ),
        sa.CheckConstraint(
            "kind IN ('broadcast','send_event','resend_tanthu')",
            name=op.f("ck_broadcast_jobs_kind"),
        ),
        sa.CheckConstraint(
            "state IN ('draft','running','paused','done','cancelled')",
            name=op.f("ck_broadcast_jobs_state"),
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_broadcast_jobs")),
    )
    op.create_table(
        "campaigns",
        sa.Column("campaign_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("interval_people", sa.Integer(), nullable=False),
        sa.Column("reward_value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("max_claims", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "interval_people > 0", name=op.f("ck_campaigns_interval_people_positive")
        ),
        sa.CheckConstraint(
            "max_claims BETWEEN 1 AND 10", name=op.f("ck_campaigns_max_claims_range")
        ),
        sa.CheckConstraint("reward_value_vnd > 0", name=op.f("ck_campaigns_reward_value_positive")),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_campaigns_window_order"),
        ),
        sa.PrimaryKeyConstraint("campaign_id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("code", name=op.f("uq_campaigns_code")),
    )
    op.create_table(
        "cluster_stats",
        sa.Column("cluster_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("n_users", sa.Integer(), nullable=False),
        sa.Column("n_verified", sa.Integer(), nullable=False),
        sa.Column("n_devices", sa.Integer(), nullable=False),
        sa.Column("total_value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "n_users >= 0 AND n_verified >= 0 AND n_devices >= 0 AND total_value_vnd >= 0",
            name=op.f("ck_cluster_stats_counters_non_negative"),
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_cluster_stats")),
    )
    op.create_table(
        "code_pool_stats",
        sa.Column("code_type", sa.Text(), nullable=False),
        sa.Column("value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("available", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("issued", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code_type IN ('tanthu','moibanbe','event','diemdanh','eventchiase')",
            name=op.f("ck_code_pool_stats_code_type_valid"),
        ),
        sa.CheckConstraint(
            "available >= 0", name=op.f("ck_code_pool_stats_available_non_negative")
        ),
        sa.CheckConstraint("issued >= 0", name=op.f("ck_code_pool_stats_issued_non_negative")),
        sa.CheckConstraint("value_vnd > 0", name=op.f("ck_code_pool_stats_value_vnd_positive")),
        sa.PrimaryKeyConstraint("code_type", "value_vnd", name=op.f("pk_code_pool_stats")),
    )
    op.create_table(
        "fraud_cases",
        sa.Column("case_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_key", sa.Text(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("dry_run_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("executed_by", sa.BigInteger(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'executed' OR (dry_run_report IS NOT NULL AND executed_by IS NOT NULL AND executed_at IS NOT NULL)",
            name=op.f("ck_fraud_cases_executed_requires_dry_run"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'dry_run', 'executed', 'dismissed')",
            name=op.f("ck_fraud_cases_status_allowed"),
        ),
        sa.CheckConstraint(
            "user_count >= 0 AND value_vnd >= 0", name=op.f("ck_fraud_cases_impact_non_negative")
        ),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_fraud_cases")),
    )
    op.create_index(
        "ix_fraud_cases_open",
        "fraud_cases",
        [sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("status IN ('open', 'dry_run')"),
    )
    op.create_table(
        "grant_types",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("label_vi", sa.Text(), nullable=False),
        sa.Column("once_per_life", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_grant_types")),
    )
    op.create_table(
        "media_assets",
        sa.Column("asset_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("file_id", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("asset_key", name=op.f("pk_media_assets")),
    )
    op.create_table(
        "membership_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("old_status", sa.Text(), nullable=True),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_events")),
    )
    op.create_index(
        "ix_membership_events_user_at", "membership_events", ["user_id", "at"], unique=False
    )
    op.create_table(
        "membership_mismatch",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("ket_qua_bang", sa.Boolean(), nullable=False),
        sa.Column("ket_qua_api", sa.Boolean(), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_mismatch")),
    )
    op.create_index(
        "ix_membership_mismatch_checked_at", "membership_mismatch", ["checked_at"], unique=False
    )
    op.create_table(
        "outbox_messages",
        sa.Column("outbox_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("state", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "visible_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("outbox_id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_outbox_messages_dedupe_key")),
    )
    op.create_index(
        "ix_outbox_claim",
        "outbox_messages",
        ["visible_at"],
        unique=False,
        postgresql_where=sa.text("state = 0"),
    )
    op.create_table(
        "referral_intents",
        sa.Column("referee_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("referee_id", name=op.f("pk_referral_intents")),
    )
    op.create_table(
        "required_chats",
        sa.Column("chat_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("invite_link", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("health", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "health IN ('healthy','degraded','unknown')", name=op.f("ck_required_chats_health")
        ),
        sa.PrimaryKeyConstraint("chat_id", name=op.f("pk_required_chats")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value_type", sa.Text(), nullable=False),
        sa.Column("label_vi", sa.Text(), nullable=False),
        sa.Column("min_value", sa.Numeric(), nullable=True),
        sa.Column("max_value", sa.Numeric(), nullable=True),
        sa.Column("sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value_type IN ('int','money_vnd','bp','seconds','bool','string','json')",
            name=op.f("ck_settings_value_type"),
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "settings_audit",
        sa.Column("audit_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_by", sa.BigInteger(), nullable=False),
        sa.Column("approved_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_settings_audit")),
    )
    op.create_index(
        "ix_settings_audit_key_at", "settings_audit", ["key", "changed_at"], unique=False
    )
    op.create_table(
        "share_event_config",
        sa.Column(
            "id",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("image_file_id", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("share_link", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_share_event_config_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_event_config")),
    )
    op.create_table(
        "system_stats",
        sa.Column(
            "id",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("total_users", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("codes_available", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("codes_issued", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_referrals", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_value_vnd", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_system_stats_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_stats")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("points_balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("checkin_streak", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_checkin_date", sa.Date(), nullable=True),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notify_optout", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("started_bot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_score", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "total_codes_received", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "total_value_received", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_active",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points_balance >= 0", name=op.f("ck_users_points_balance_non_negative")
        ),
        sa.CheckConstraint("risk_score BETWEEN 0 AND 100", name=op.f("ck_users_risk_score_range")),
        sa.CheckConstraint(
            "total_codes_received >= 0", name=op.f("ck_users_total_codes_non_negative")
        ),
        sa.CheckConstraint(
            "total_value_received >= 0", name=op.f("ck_users_total_value_non_negative")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_audience",
        "users",
        [sa.literal_column("last_active DESC")],
        unique=False,
        postgresql_where=sa.text(
            "blocked_at IS NULL AND notify_optout = false AND started_bot_at IS NOT NULL"
        ),
    )
    op.create_index(
        "uq_users_username_lower",
        "users",
        [sa.literal_column("lower(username)")],
        unique=True,
        postgresql_where=sa.text("username IS NOT NULL"),
    )
    op.create_table(
        "admin_users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("added_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner','admin','cskh','ketoan')", name=op.f("ck_admin_users_role")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_admin_users_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_admin_users")),
    )
    op.create_index(
        "ix_admin_users_active",
        "admin_users",
        ["role"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "broadcast_targets",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("state", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.SmallInteger(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["broadcast_jobs.job_id"],
            name=op.f("fk_broadcast_targets_job_id_broadcast_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", "user_id", name=op.f("pk_broadcast_targets")),
    )
    op.create_index(
        "ix_bt_claim",
        "broadcast_targets",
        ["job_id", "next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("state = 0"),
    )
    op.create_index(
        "ix_bt_janitor",
        "broadcast_targets",
        ["sent_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND tg_message_id IS NOT NULL"),
    )
    op.create_table(
        "checkins",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("points_delta", sa.BigInteger(), server_default=sa.text("2000"), nullable=False),
        sa.Column("streak_after", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("points_delta > 0", name=op.f("ck_checkins_points_delta_positive")),
        sa.CheckConstraint("streak_after >= 1", name=op.f("ck_checkins_streak_after_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_checkins_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", "business_date", name=op.f("pk_checkins")),
    )
    op.create_table(
        "codes",
        sa.Column("code_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code_value", sa.Text(), nullable=False),
        sa.Column("code_type", sa.Text(), nullable=False),
        sa.Column("value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'available'"), nullable=False),
        sa.Column("reserved_for", sa.BigInteger(), nullable=True),
        sa.Column("reserved_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("batch_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "code_type IN ('tanthu','moibanbe','event','diemdanh','eventchiase')",
            name=op.f("ck_codes_code_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('available','reserved','issued','revoked')",
            name=op.f("ck_codes_status_valid"),
        ),
        sa.CheckConstraint("value_vnd > 0", name=op.f("ck_codes_value_vnd_positive")),
        sa.ForeignKeyConstraint(
            ["reserved_for"],
            ["users.user_id"],
            name=op.f("fk_codes_reserved_for_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("code_id", name=op.f("pk_codes")),
    )
    op.create_index(
        "ix_codes_pick",
        "codes",
        ["code_type", "value_vnd", "code_id"],
        unique=False,
        postgresql_where=sa.text("status = 'available'"),
    )
    op.create_index(
        "ix_codes_reap",
        "codes",
        ["reserved_until"],
        unique=False,
        postgresql_where=sa.text("status = 'reserved'"),
    )
    op.create_index("uq_codes_value", "codes", ["code_value"], unique=True)
    op.create_table(
        "events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("media_asset_key", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("event_type IN ('dap_hop')", name=op.f("ck_events_event_type_valid")),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["broadcast_jobs.job_id"],
            name=op.f("fk_events_job_id_broadcast_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_key"],
            ["media_assets.asset_key"],
            name=op.f("fk_events_media_asset_key_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_active",
        "events",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "group_memberships",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_member", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("trust_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('event','poll','backfill')", name=op.f("ck_group_memberships_source")
        ),
        sa.CheckConstraint(
            "status IN ('creator','administrator','member','restricted','left','kicked')",
            name=op.f("ck_group_memberships_status"),
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["required_chats.chat_id"],
            name=op.f("fk_group_memberships_chat_id_required_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "chat_id", name=op.f("pk_group_memberships")),
    )
    op.create_index("ix_gm_chat", "group_memberships", ["chat_id", "status"], unique=False)
    op.create_index(
        "ix_gm_user_member",
        "group_memberships",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_member"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_idempotency_records_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("idempotency_key", name=op.f("pk_idempotency_records")),
    )
    op.create_index("ix_idem_gc", "idempotency_records", ["expires_at"], unique=False)
    op.create_table(
        "identity_clusters",
        sa.Column("cluster_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_identity_clusters_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("cluster_id", "user_id", name=op.f("pk_identity_clusters")),
    )
    op.create_index("ix_clusters_user", "identity_clusters", ["user_id"], unique=False)
    op.create_table(
        "identity_signals",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("signal_type", sa.Text(), nullable=False),
        sa.Column("signal_value", sa.Text(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("hits", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "signal_type IN ('ip', 'ip24', 'asn', 'device_hash', 'ua_hash', 'device_raw')",
            name=op.f("ck_identity_signals_signal_type_allowed"),
        ),
        sa.CheckConstraint("hits > 0", name=op.f("ck_identity_signals_hits_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_identity_signals_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "signal_type", "signal_value", name=op.f("pk_identity_signals")
        ),
    )
    op.create_index(
        "ix_signals_reverse", "identity_signals", ["signal_type", "signal_value"], unique=False
    )
    op.create_table(
        "points_ledger",
        sa.Column("entry_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("delta", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ref_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('checkin', 'redeem', 'admin_adjust', 'reversal')",
            name=op.f("ck_points_ledger_reason_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_points_ledger_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_points_ledger")),
        sa.UniqueConstraint(
            "user_id", "reason", "ref_key", name="uq_points_ledger_user_id_reason_ref_key"
        ),
    )
    op.create_table(
        "referrals",
        sa.Column("referee_id", sa.BigInteger(), nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.Text(), nullable=True),
        sa.Column("device_hash", sa.Text(), nullable=True),
        sa.Column("risk_score", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("referrer_id <> referee_id", name=op.f("ck_referrals_no_self_referral")),
        sa.CheckConstraint(
            "risk_score IS NULL OR risk_score BETWEEN 0 AND 100",
            name=op.f("ck_referrals_risk_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["referee_id"],
            ["users.user_id"],
            name=op.f("fk_referrals_referee_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.user_id"],
            name=op.f("fk_referrals_referrer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("referee_id", name=op.f("pk_referrals")),
    )
    op.create_index(
        "ix_referrals_referrer",
        "referrals",
        ["referrer_id"],
        unique=False,
        postgresql_where=sa.text("qualified_at IS NOT NULL"),
    )
    op.create_table(
        "risk_assessments",
        sa.Column("assessment_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('shadow', 'enforce')", name=op.f("ck_risk_assessments_mode_allowed")
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name=op.f("ck_risk_assessments_score_range")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_risk_assessments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("assessment_id", name=op.f("pk_risk_assessments")),
    )
    op.create_index(
        "ix_risk_assessments_user_time",
        "risk_assessments",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "signal_owners",
        sa.Column("signal_type", sa.Text(), nullable=False),
        sa.Column("signal_value", sa.Text(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("first_user_id", sa.BigInteger(), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "signal_type IN ('ip', 'ip24', 'asn', 'device_hash', 'ua_hash', 'device_raw')",
            name=op.f("ck_signal_owners_signal_type_allowed"),
        ),
        sa.CheckConstraint(
            "user_count >= 0", name=op.f("ck_signal_owners_user_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["first_user_id"],
            ["users.user_id"],
            name=op.f("fk_signal_owners_first_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("signal_type", "signal_value", name=op.f("pk_signal_owners")),
    )
    op.create_table(
        "user_bans",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("banned_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "banned_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("unbanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["fraud_cases.case_id"],
            name=op.f("fk_user_bans_case_id_fraud_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_user_bans_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_bans")),
    )
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("refs_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("refs_qualified", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("value_total", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("checkin_streak", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_user_stats_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_stats")),
    )
    op.create_index(
        "ix_user_stats_checkin_streak",
        "user_stats",
        [sa.literal_column("checkin_streak DESC")],
        unique=False,
    )
    op.create_index(
        "ix_user_stats_refs_total",
        "user_stats",
        [sa.literal_column("refs_total DESC")],
        unique=False,
    )
    op.create_index(
        "ix_user_stats_value_total",
        "user_stats",
        [sa.literal_column("value_total DESC")],
        unique=False,
    )
    op.create_table(
        "verification_events",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("ip_24", postgresql.CIDR(), nullable=True),
        sa.Column("asn", sa.Integer(), nullable=True),
        sa.Column("country", sa.CHAR(length=2), nullable=True),
        sa.Column("device_hash", sa.Text(), nullable=True),
        sa.Column("ua_hash", sa.Text(), nullable=True),
        sa.Column("initdata_valid", sa.Boolean(), nullable=False),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("risk_score", sa.SmallInteger(), nullable=False),
        sa.Column(
            "reasons",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('verify', 'recheck')",
            name=op.f("ck_verification_events_event_type_allowed"),
        ),
        sa.CheckConstraint(
            "verdict IN ('pass', 'flag', 'block')",
            name=op.f("ck_verification_events_verdict_allowed"),
        ),
        sa.CheckConstraint(
            "risk_score BETWEEN 0 AND 100", name=op.f("ck_verification_events_risk_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_verification_events_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_verification_events")),
    )
    op.create_index(
        "ix_verification_events_user_time",
        "verification_events",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "code_grants",
        sa.Column("grant_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("grant_key", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("grant_type", sa.Text(), nullable=False),
        sa.Column("code_id", sa.BigInteger(), nullable=True),
        sa.Column("value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'reserved'"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "reason",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.Column("tg_message_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "grant_type IN ('tanthu','referral_milestone','event_box','points_redeem','share_event','admin_manual')",
            name=op.f("ck_code_grants_grant_type_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('reserved','delivered','revoked')", name=op.f("ck_code_grants_state_valid")
        ),
        sa.CheckConstraint("value_vnd > 0", name=op.f("ck_code_grants_value_vnd_positive")),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["codes.code_id"],
            name=op.f("fk_code_grants_code_id_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grant_type"],
            ["grant_types.code"],
            name=op.f("fk_code_grants_grant_type_grant_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_code_grants_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("grant_id", name=op.f("pk_code_grants")),
    )
    op.create_index(
        "ix_grants_recent", "code_grants", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(
        "ix_grants_user",
        "code_grants",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_grant_once_semantic",
        "code_grants",
        ["user_id", "grant_type"],
        unique=True,
        postgresql_where=sa.text("grant_type IN ('tanthu','share_event')"),
    )
    op.create_index(
        "uq_grants_code",
        "code_grants",
        ["code_id"],
        unique=True,
        postgresql_where=sa.text("code_id IS NOT NULL"),
    )
    op.create_index("uq_grants_key", "code_grants", ["grant_key"], unique=True)
    op.create_table(
        "code_ledger",
        sa.Column("entry_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("prev_hash", sa.LargeBinary(), nullable=True),
        sa.Column("entry_hash", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("grant_id", sa.BigInteger(), nullable=False),
        sa.Column("code_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.SmallInteger(), nullable=False),
        sa.Column("value_vnd", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ref_entry_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN (1, -1)", name=op.f("ck_code_ledger_direction_valid")),
        sa.CheckConstraint("value_vnd > 0", name=op.f("ck_code_ledger_value_vnd_positive")),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["codes.code_id"],
            name=op.f("fk_code_ledger_code_id_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["code_grants.grant_id"],
            name=op.f("fk_code_ledger_grant_id_code_grants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ref_entry_id"],
            ["code_ledger.entry_id"],
            name=op.f("fk_code_ledger_ref_entry_id_code_ledger"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_code_ledger_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_code_ledger")),
    )
    op.create_table(
        "event_participations",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("code_grant_id", sa.BigInteger(), nullable=True),
        sa.Column("window_source", sa.Text(), nullable=False),
        sa.Column(
            "participated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result IN ('empty', '5k', '10k', '20k', '50k', '88k', 'out_of_stock')",
            name=op.f("ck_event_participations_result_valid"),
        ),
        sa.CheckConstraint(
            "window_source IN ('per_recipient', 'event_created')",
            name=op.f("ck_event_participations_window_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["code_grant_id"],
            ["code_grants.grant_id"],
            name=op.f("fk_event_participations_code_grant_id_code_grants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_participations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_event_participations_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", "event_id", name=op.f("pk_event_participations")),
    )
    op.create_index(
        "ix_event_participations_event",
        "event_participations",
        ["event_id", "result"],
        unique=False,
    )
    op.create_table(
        "referral_rewards",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("tier_no", sa.SmallInteger(), nullable=False),
        sa.Column("code_grant_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tier_no BETWEEN 1 AND 10", name=op.f("ck_referral_rewards_tier_no_range")
        ),
        sa.ForeignKeyConstraint(
            ["code_grant_id"],
            ["code_grants.grant_id"],
            name=op.f("fk_referral_rewards_code_grant_id_code_grants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_referral_rewards_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", "tier_no", name=op.f("pk_referral_rewards")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("referral_rewards")
    op.drop_index("ix_event_participations_event", table_name="event_participations")
    op.drop_table("event_participations")
    op.drop_table("code_ledger")
    op.drop_index("uq_grants_key", table_name="code_grants")
    op.drop_index(
        "uq_grants_code", table_name="code_grants", postgresql_where=sa.text("code_id IS NOT NULL")
    )
    op.drop_index(
        "uq_grant_once_semantic",
        table_name="code_grants",
        postgresql_where=sa.text("grant_type IN ('tanthu','share_event')"),
    )
    op.drop_index("ix_grants_user", table_name="code_grants")
    op.drop_index("ix_grants_recent", table_name="code_grants")
    op.drop_table("code_grants")
    op.drop_index("ix_verification_events_user_time", table_name="verification_events")
    op.drop_table("verification_events")
    op.drop_index("ix_user_stats_value_total", table_name="user_stats")
    op.drop_index("ix_user_stats_refs_total", table_name="user_stats")
    op.drop_index("ix_user_stats_checkin_streak", table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_table("user_bans")
    op.drop_table("signal_owners")
    op.drop_index("ix_risk_assessments_user_time", table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_index(
        "ix_referrals_referrer",
        table_name="referrals",
        postgresql_where=sa.text("qualified_at IS NOT NULL"),
    )
    op.drop_table("referrals")
    op.drop_table("points_ledger")
    op.drop_index("ix_signals_reverse", table_name="identity_signals")
    op.drop_table("identity_signals")
    op.drop_index("ix_clusters_user", table_name="identity_clusters")
    op.drop_table("identity_clusters")
    op.drop_index("ix_idem_gc", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(
        "ix_gm_user_member", table_name="group_memberships", postgresql_where=sa.text("is_member")
    )
    op.drop_index("ix_gm_chat", table_name="group_memberships")
    op.drop_table("group_memberships")
    op.drop_index("ix_events_active", table_name="events", postgresql_where=sa.text("is_active"))
    op.drop_table("events")
    op.drop_index("uq_codes_value", table_name="codes")
    op.drop_index(
        "ix_codes_reap", table_name="codes", postgresql_where=sa.text("status = 'reserved'")
    )
    op.drop_index(
        "ix_codes_pick", table_name="codes", postgresql_where=sa.text("status = 'available'")
    )
    op.drop_table("codes")
    op.drop_table("checkins")
    op.drop_index(
        "ix_bt_janitor",
        table_name="broadcast_targets",
        postgresql_where=sa.text("deleted_at IS NULL AND tg_message_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_bt_claim", table_name="broadcast_targets", postgresql_where=sa.text("state = 0")
    )
    op.drop_table("broadcast_targets")
    op.drop_index(
        "ix_admin_users_active",
        table_name="admin_users",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("admin_users")
    op.drop_index(
        "uq_users_username_lower",
        table_name="users",
        postgresql_where=sa.text("username IS NOT NULL"),
    )
    op.drop_index(
        "ix_users_audience",
        table_name="users",
        postgresql_where=sa.text(
            "blocked_at IS NULL AND notify_optout = false AND started_bot_at IS NOT NULL"
        ),
    )
    op.drop_table("users")
    op.drop_table("system_stats")
    op.drop_table("share_event_config")
    op.drop_index("ix_settings_audit_key_at", table_name="settings_audit")
    op.drop_table("settings_audit")
    op.drop_table("settings")
    op.drop_table("required_chats")
    op.drop_table("referral_intents")
    op.drop_index(
        "ix_outbox_claim", table_name="outbox_messages", postgresql_where=sa.text("state = 0")
    )
    op.drop_table("outbox_messages")
    op.drop_index("ix_membership_mismatch_checked_at", table_name="membership_mismatch")
    op.drop_table("membership_mismatch")
    op.drop_index("ix_membership_events_user_at", table_name="membership_events")
    op.drop_table("membership_events")
    op.drop_table("media_assets")
    op.drop_table("grant_types")
    op.drop_index(
        "ix_fraud_cases_open",
        table_name="fraud_cases",
        postgresql_where=sa.text("status IN ('open', 'dry_run')"),
    )
    op.drop_table("fraud_cases")
    op.drop_table("code_pool_stats")
    op.drop_table("cluster_stats")
    op.drop_table("campaigns")
    op.drop_table("broadcast_jobs")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("asn_policy")
    op.drop_table("admin_permissions")
    # ### end Alembic commands ###
